# Generated by Django 4.0.5 on 2022-11-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anonymity',
            field=models.BooleanField(default=False),
        ),
    ]
