# Generated by Django 4.0.5 on 2022-11-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_article_anonymity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='anonymity',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
