# Generated by Django 4.0.5 on 2022-09-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
