# Generated by Django 4.0.5 on 2022-09-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
