# Generated by Django 3.2.15 on 2022-09-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
