# Generated by Django 3.2.15 on 2022-11-16 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='fri1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fri6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='月1'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='月2'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='mon6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thu1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thu2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thu3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thu4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thu5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thu6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='tue6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wed1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wed2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wed3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wed4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wed5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='wed6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
    ]
