# Generated by Django 3.2.15 on 2022-10-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/icon_images'),
        ),
    ]
