# Generated by Django 3.2.15 on 2022-10-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_person_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30, null=True)),
                ('t_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fri1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('fri2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('fri3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('fri4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('fri5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('fri6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('mon1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='月1')),
                ('mon2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='月2')),
                ('mon3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('mon4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('mon5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('mon6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('thu1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('thu2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('thu3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('thu4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('thu5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('thu6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('tue1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('tue2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('tue3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('tue4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('tue5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('tue6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('wed1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('wed2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('wed4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('wed5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
                ('wed6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='timetable',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.timetable', verbose_name='時間割'),
            preserve_default=False,
        ),
    ]
