# Generated by Django 3.2.15 on 2022-11-01 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221026_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='wed3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.subject', verbose_name='科目名'),
        ),
    ]
